Global:
  use_gpu: true
  use_xpu: false
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/db_mv3_prod_hier_text/
  save_epoch_step: 500
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 5000]
  cal_metric_during_train: False
  pretrained_model: pretrained_models/det/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: /tmp/hssk5.jpg
  save_res_path: ./output/det_db/predicts_db.txt

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
    disable_se: false
  Neck:
    #name: RSEFPN
    #out_channels: 96
    name: LKPAN
    out_channels: 96
    mode: lite
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
  weights: [1, 1, 1]

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 5000
  unclip_ratio: 1.5 # Update this value if you change the shrink_ratio in MakeShrinkMap

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /data2/storage/text_det/
    label_file_list:
      #- /data2/storage/text_det/craft_gen/train_v2.jsonl
      #- /data2/storage/text_det/einvoice/einvoice_train_words_v3.jsonl
      #- /data2/storage/text_det/synthtext/train_new_v2.jsonl
      #- /data2/storage/text_det/docile_manual/train_v2.jsonl
      #- /data2/storage/text_det/vbhc_31032024/train_v2.jsonl
      #- /data2/storage/text_det/cord-v2/train_v2.jsonl
      #- /data2/storage/text_det/vintext/train_v2.jsonl
      - /data2/storage/text_det/idl/train_v2.jsonl
      - /data2/storage/text_det/google_hier_text/train_v2.jsonl
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - AlbumentationsAugment:
          augmenter_args:
            - { 'type': HorizontalFlip, 'args': {'p': 0.5} }
            - { 'type': Rotate, 'args': {'limit': [-10, 10]}} 
            - { 'type': RandomScale, 'args': {'scale_limit': [0.5, 3.0], 'p': 1.0} }
      - EastRandomCropData:
          size: [1024, 1024]
          max_tries: 10
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4 # Increase to 0.8 if your text region is large, and update the unclip_ratio in PostProcess to 0.2
          min_text_size: 2
          ignore_if_not_found: false
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list, *_mask is used to ignore regions
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 4
    num_workers: 8
    use_shared_memory: True

Eval:
  dataset:
    name: SimpleDataSet
    ratio_list: 1.0
    data_dir: /data2/storage/text_det/
    label_file_list:
      #- /data2/storage/text_det/craft_gen/test_v2.jsonl
      #- /data2/storage/text_det/vbhc_31032024/test_v2.jsonl
      #- /data2/storage/text_det/einvoice/einvoice_test_words_v3.jsonl
      #- /data2/storage/text_det/cord-v2/test_v2.jsonl
      #- /data2/storage/text_det/docile_manual/test_v2.jsonl
      #- /data2/storage/text_det/vintext/test_v2.jsonl
      #- /data2/storage/text_det/idl/test_v2.jsonl
      - /data2/storage/text_det/google_hier_text/test_v2.jsonl
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
          image_shape: [1600, 1600]
          keep_ratio: true
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 8
    use_shared_memory: True
